services:
  app-server:
    build: src/server

    volumes:
      - ./src/server/nginx.conf:/etc/nginx/conf.d/site.conf:ro
    ports:
      - "80:80"

  app-certbot:
    ports:
      - "6000:80"
    env_file:
      - .env
    volumes:
      - cert-dir:/etc/cert
    build:
      context: src/certbot
      args:
        DOMAIN_EMAIL: ${DOMAIN_EMAIL}
        DOMAIN_URL: ${DOMAIN_URL}

volumes:
  cert-dir:
    external: true
