services:
  certbot:
    ports:
      - "6000:80"
    env_file:
      - .env
    volumes:
      - cert-dir:/etc/cert
    build:
      context: ./certbot
      dockerfile: Dockerfile
      args:
        DOMAIN_EMAIL: ${DOMAIN_EMAIL}
        DOMAIN_URL: ${DOMAIN_URL}

volumes:
  cert-dir:
    external: true
